# Gradle / JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# AndroidX????
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Compose
android.defaults.buildfeatures.buildconfig=false